server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    user:
      name: admin
      password: adminpassword
  datasource:
    url: jdbc:h2:file:./data/headhanterdb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console

  # --- НАСТРОЙКИ JPA / HIBERNATE ---
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  # --- НАСТРОЙКИ LIQUIBASE ---
  liquibase:
    enabled: false

  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: ALWAYS
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    cache: false

logging:
  level:
    root: INFO
    com.example.headhanter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG