server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:headhanterdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  sql:
    init:
      mode: never

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    com.example.headhanter: DEBUG
    org.springframework.security: DEBUG